### ISSUE TITLE
Segmentation fault in function flom_trace

### ISSUE THREAD

**Issue by tiian** [tiian/flom#4]
With some trace masks, flom_trace function generates a segmentation fault in function vsnprintf.
Environment:
Ubuntu 10.04 (64 bit), virtual (KVM).
FLOM_TRACE_MASK=0xff
Failing case test: "Use case 16 (2/8)"
Stack trace from core dump analysis:

`Core was generated by `/home/tiian/flom/src/.libs/lt-flom -e n -r ABC[1] -A 224.0.0.1 -- sleep 1'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002b6369a9899d in _IO_vfprintf_internal (s=0x7fff30524170, 
    format=<value optimized out>, ap=0x7fff30524360) at vfprintf.c:1623
1623	vfprintf.c: No such file or directory.
	in vfprintf.c
(gdb) bt
#0  0x00002b6369a9899d in _IO_vfprintf_internal (s=0x7fff30524170, 
    format=<value optimized out>, ap=0x7fff30524360) at vfprintf.c:1623
#1  0x00002b6369b51410 in ___vsnprintf_chk (
    s=0x7fff305243bd "flom_msg_free: peerid=x1fa77e0] flom_client_wait_lock: the resource is busy, looping again...\n", maxlen=<value optimized out>, flags=1, 
    slen=<value optimized out>, 
    format=0x2b63693afbf8 "flom_msg_free: peerid=%s\n", args=0x7fff30524360)
    at vsnprintf_chk.c:65
#2  0x00002b63693a8f97 in vsnprintf (
    fmt=0x2b63693afbf8 "flom_msg_free: peerid=%s\n")
    at /usr/include/bits/stdio2.h:78
#3  flom_trace (fmt=0x2b63693afbf8 "flom_msg_free: peerid=%s\n")
    at flom_trace.c:147
#4  0x00002b636939c3c3 in flom_msg_free (msg=0x7fff30525110) at flom_msg.c:152
#5  0x00002b636939193b in flom_client_wait_lock (conn=0x1fb8b80, 
    msg=0x7fff30525110, timeout=-1) at flom_client.c:1149
#6  0x00002b636939204c in flom_client_lock (config=0x0, conn=0x1fb8b80, 
    timeout=<value optimized out>, element=<value optimized out>)
    at flom_client.c:1000
#7  0x0000000000402f0e in main (argc=1, argv=0x7fff305256d8) at main.c:423
`

The issue could be more widespread because in the previous versions it was not possible to use a FLOM_TRACE_MASK to run case tests.

**Comment by tiian** [comment]
Release 1.2.0 fixes the bug.
